require("ivantoniev.set")
require("ivantoniev.plugins")
require("ivantoniev.plugin_config.treesitter")
require("ivantoniev.plugin_config.comment")
require("ivantoniev.plugin_config.cmp")
require("ivantoniev.remapping/remap")
require("ivantoniev.remapping/lsp_remap")
require("ivantoniev.remapping/trouble_remap")
