require("ivantoniev.set")
require("ivantoniev.lazy-setup")
require("ivantoniev.remapping/remap")
require("ivantoniev.remapping/lsp_remap")
require("ivantoniev.remapping/trouble_remap")
require("ivantoniev.plugin_config.cmp")
require("ivantoniev.plugin_config.copilot")
