local Plug = vim.fn["plug#"]

vim.call("plug#begin", "~/.config/nvim/plugged")
  Plug("folke/tokyonight.nvim", { branch = "main" })
  Plug("mhartington/oceanic-next")
  Plug("vim-airline/vim-airline")
  Plug("ayu-theme/ayu-vim")
  Plug("drewtempelmeyer/palenight.vim")
  Plug("tssm/fairyfloss.vim")
  Plug("w0rp/ale")
  Plug("rakr/vim-one")
  Plug("tpope/vim-fugitive")
  Plug("tpope/vim-sensible")
  Plug("scrooloose/nerdTree")
  Plug("ctrlpvim/ctrlp.vim")
  Plug("junegunn/fzf", { ["do"] = vim.fn["fzf#install"] })
  Plug("junegunn/fzf.vim")
  Plug("airblade/vim-gitgutter")
  Plug("APZelos/blamer.nvim")
  Plug("vim-test/vim-test")
  Plug("kchmck/vim-coffee-script")
  Plug("farmergreg/vim-lastplace")
  Plug("kevinhwang91/nvim-ufo")
vim.call("plug#end")
